# Generated by Django 4.0.1 on 2022-02-10 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sabina', '0002_alter_about_career_alter_home_updated_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='project/')),
                ('link', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='Portfolio',
        ),
    ]
