# Generated by Django 4.0.1 on 2022-03-22 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sabina', '0004_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='level',
            field=models.CharField(max_length=80),
        ),
    ]
