# Generated by Django 4.0.1 on 2022-03-25 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sabina', '0006_contact_alter_home_greetings_1_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
